NMD-server/store/products/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from products.views import (CartView, FavoritesView, basket_add, basket_remove,
                            cart_add_plus_one, cart_del_minus_one,
                            favorites_add, favorites_remove, item_info,
                            products, remove_all_user_baskets,
                            remove_all_user_favorites, reset_filters,cart_confirm,catalogue)
from django.views.decorators.cache import cache_page

app_name = 'products'
urlpatterns = [
    path('', login_required(products), name='products'),
    path('page/<int:page>/', login_required(products), name='paginator'),
    path('reset/', login_required(reset_filters), name='reset_filters'),
    path('item_info/<str:product_id>', login_required(item_info), name='item_info'),
    path('baskets/add/<str:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>', basket_remove, name='basket_remove'),
    path('cart/', login_required(CartView.as_view()), name='cart'),
    path('baskets/remove/', remove_all_user_baskets, name='remove_all_user_baskets'),
    path('cart/add/<int:basket_id>/', cart_add_plus_one, name='cart_add_plus_one'),
    path('cart/del/<int:basket_id>', cart_del_minus_one, name='cart_del_minus_one'),
    path('favorites/add/<str:product_id>', login_required(favorites_add), name='favorites_add'),
    path('favorites/', login_required(FavoritesView.as_view()), name='favorites'),
    path('favorites/remove/<int:favorite_id>/', favorites_remove, name='favorites_remove'),
    path('favorites/remove/', remove_all_user_favorites, name='remove_all_user_favorites'),
    path('cart/cart_confirm/', cart_confirm,name='cart_confirm'),
    path('catalogue/',catalogue,name='catalogue')
]

NMD-server/store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('products/', include('products.urls', namespace='products')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NMD-server/store/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path
from .views import *



app_name = 'users'
urlpatterns = [
    path('', index, name='index'),
    path('registration/', registration, name='registration'),
    path('registration_confirm/', registration_confirm, name='registration_confirm'),
    path('recovery/', recovery, name='recovery'),
    path('profile/<int:pk>',profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),

]

NMD-server/store/users/models.py
from django.contrib.auth.models import AbstractUser, UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _

from django.db import models
from image_cropping import ImageRatioField

from PIL import Image
from django.db import models
from image_cropping import ImageCropField, ImageRatioField


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
        null=True,
        blank=True,
    )
    email = models.EmailField(_("email address"), unique=True)
    image = models.ImageField(upload_to='users_images', blank=True, null=True)
    # image = ImageCropField(blank=True, upload_to='users_images', null= True)


    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    # def save(self):
    #     super().save()  # saving image first
    #     img = Image.open(self.image.path) # Open image using self
    #     print(img.height)
    #     print(img.width)
    #     percent_ratio= 0.1
    #
    #
    #     if img.height > 180 or img.width > 180:
    #         new_img = (174,171)
    #         print(new_img)
    #
    #         img.thumbnail(new_img)
    #         img.save(self.image.path)


class Image(models.Model):
    file = models.ImageField(upload_to='users_images')
    uploaded = models.DateTimeField(auto_now_add=True)

NMD-server/store/users/forms.py
from django import forms
from django.contrib.auth import authenticate, password_validation
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm, PasswordChangeForm)
from django.utils.translation import gettext_lazy as _

from .models import User, Image
from django import forms
from image_cropping import ImageCropWidget


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'class': 'input', 'placeholder': 'Email/Почта', 'name': 'email',
        'type': 'email'
    }))
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
        required=False
    )

    class Meta:
        model = User
        fields = ('email',)


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(required=False)
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'class': 'input', 'placeholder': 'Email/Почта', 'name': 'email',
        'type': 'email'
    }))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': 'Password/Пароль', 'name': 'password',
        'type': 'password'
    }))

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email is not None and password:
            self.user_cache = authenticate(
                self.request, email=email, password=password
            )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    class Meta:
        model = User
        fields = ('email', 'password')


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-input', 'type': 'text', 'name': 'username', 'placeholder': 'Имя Пользователя',
        'id': 'username_id'
    }), required=False)
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-input', 'type': 'text', 'name': 'first_name', 'placeholder': 'Имя', 'id': 'first_name_id'
    }), required=False)

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-input', 'type': 'text', 'name': 'last_name', 'placeholder': 'Фамилия', 'id': 'last_name_id'
    }), required=False)

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-input', 'type': 'email', 'name': 'email', 'placeholder': 'Эл.Почта', 'readonly': True,
        'style': 'color:#C0BFBF;', 'id': 'user_email_id',
    }))

    image = forms.ImageField(widget=forms.FileInput(attrs={
        'type': 'file', 'name': 'file', 'accept': 'image/*', 'id': 'id_file',
    }), required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'image',)


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('file',)


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(
        attrs={'class': 'input', 'placeholder': 'Старый пароль'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(
        attrs={'class': 'input', 'placeholder': 'Новый пароль'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(
        attrs={'class': 'input', 'placeholder': 'Новый пароль еще раз'}))

NMD-server/store/users/views.py
from django.conf import settings
from django.contrib import auth
from django.contrib.auth.views import PasswordChangeView
from django.core.mail import send_mail
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render





from .models import User, Image
from .forms import UserLoginForm, UserProfileForm, UserRegistrationForm, UserPasswordChangeForm


def index(request):
    if request.user.is_authenticated and request.user.id is not None:
        return HttpResponseRedirect(reverse('products:products'))
    else:
        if request.method == 'POST':
            form = UserLoginForm(data=request.POST)
            if form.is_valid():
                email = request.POST['email']
                password = request.POST['password']
                user = auth.authenticate(email=email, password=password)
                if user:
                    auth.login(request,user)
                    return HttpResponseRedirect(reverse('products:products'))
            else:
                print(form.cleaned_data)
                print(form.errors)
                print(form.non_field_errors())
                print(form.errors.as_data())
        else:
            form = UserLoginForm()
        context = {
            'title': "Вход/Регирстрация",
            'header': "Сайт предзаказа для сотрудников",
            'form_label': "Авторизация",
            'form': form,
        }

        return render(request,'users/index.html',context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            created_user = User.objects.last()
            password = User.objects.make_random_password(length=15)
            created_user.set_password(password)
            created_user.save(update_fields=['password'])
            created_user.username = created_user.email
            created_user.save()
            print(password)
            send_mail('Ваш Пароль от сайта Никамед предзаказ', f'ВАШ ПАРОЛЬ: {password}', settings.EMAIL_HOST_USER, [f'{created_user.email}'])
            return HttpResponseRedirect(reverse('users:registration_confirm'))
        else:
            context = {
                'title': "Регирстрация",
                'header': "Регистрация",
                'form_label': "Регистрация",
                'form': form
            }
            print(form.errors)
            return render(request, 'users/registration.html', context)
    form = UserRegistrationForm()
    context = {
        'title': "Регирстрация",
        'header': "Регистрация",
        'form_label': "Регистрация",
        'form': form,
    }
    return render(request, 'users/registration.html', context)

def registration_confirm(request):
    context = {
        'title': "Подтверждение регистрации",
        'header': "Подтверждение регистрации",
        'form_label': "Вы успешно зарегистрированы. Пароль отправлен на вашу почту. Введите почту и пароль на главной странице для входа на сайт.",
    }
    return render(request, 'users/registration_confirm.html', context)


def recovery(request):
    context = {
        'title': "Восстановление данных",
        'header': "Восстановление данных",
        'form_label': "Восстановить пароль",
    }
    return render(request, 'users/recovery.html', context)

def profile(request,pk):
    if request.method == 'POST':

        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        print(request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.META['HTTP_REFERER'])
    else:
        form = UserProfileForm(instance=request.user)
    context = {
        'title': "Личный кабинет",
        'form': form,


    }
    return render(request, 'users/profile.html', context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('users:index'))
class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {'title': "Изменение пароля",
                     'form_label':'Изменение пароля'}

NMD-server/store/users/templates/users/index.html
{% extends 'users/base_login.html'%}


{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/index.css' %}">
{% endblock%}

{% block logo %}
    <a href="{% url 'users:index' %}">
        <img src="{% static 'users/images/NMD_logo.jpg' %}" alt="альтернативный текст" width="95px" height="86px">
    </a>

{% endblock %}
{% block header-title%}
    <div class="header-title"> {{header}}</div>
{% endblock %}


{% block action_button %}
{% if form.non_field_errors %}
    <div class="container">
        <div class="alert alert-dismissible fade in">
            <a href="#" class="alert-close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>{{form.non_field_errors}}</strong>
        </div>
    </div>
{%endif%}
<form action="{% url 'users:index' %}" method="post">
    {% csrf_token %}
    {{ form.email}}
    {{ form.password}}
    <button class="btn" type="submit">Вход</button>
    <a href="{% url 'users:registration'%}">
        <button class="btn" type="button">Регистрация</button>
    </a>
    <div class="checkbox-group">


        <a class="under-signup" href="{% url 'users:recovery' %}">Забыли пароль?</a>
    </div>
</form>
{% endblock %}

NMD-server/store/users/templates/users/password_change_done.html
{% extends 'products/base_products.html'%}

{% load static %}

{% load products_tags %}


{% block css%}
<link rel="stylesheet" type="text/css" href="{% static 'products/css/products.css' %}">


{% endblock %}

{% block logo %}
<a href="{% url 'products:products' %}">
    <img src="{% static 'products/images/NMD_logo.jpg' %}" alt="альтернативный текст" width="95px" height="86px">
</a>
{% endblock %}

{% block content%}
<div class="content">
    <div class="catalogue-info">
        <div>
            <h3>Пароль успешно изменен!</h3>
        </div>
        <div class="catalogue-back-btn">
            <a class="btn-filter" href="{% url 'products:products' %}">На главную</a>

        </div>
    </div>


</div>

{% endblock %}

NMD-server/store/users/templates/users/password_change_form.html
{% extends 'index.html' %}
{% load static %}
{% block css%}
<link rel="stylesheet" href="{% static 'users/css/index.css' %}">
{% endblock %}


{% block action_button %}


<form method="post">
    {% csrf_token %}

    {{ form.old_password }}
    {{ form.new_password1 }}
    {{ form.new_password2 }}

    <div class="adjust-change-pass">
        <button class="btn-filter" type="submit">Изменить пароль</button>
    </div>

    <div class="form-errors">
        <div class="pass_change_errors_msg">
            {% for f in form %}
            {{ form.non_field_errors }}
            {{ f.errors }}
            {% endfor %}
        </div>
    </div>

</form>
{% endblock %}

NMD-server/store/users/templates/users/profile.html
{% extends 'products/base_products.html'%}
{% load cropping %}

{% load static %}

{% block css%}
<link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}

{% block logo %}
<a href="{% url 'products:products' %}">
    <img src="{% static 'users/images/NMD_logo.jpg' %}" alt="альтернативный текст" width="95px" height="86px">
</a>
{% endblock %}


{% block content %}

<div class="profile">

    <div class="profile-title">Профиль</div>
    <div class="profile-form-group">

        <form id="profile_form" action="{% url 'users:profile' user.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}


            <div id="image-box" class="image-box">
                <div class="profile-image" id="profile_image">

                    {% if user.image %}
                    <img id="output" src="{{ user.image.url }}">
                    {% else %}
                    <img src="{% static 'users/images/default_avatar.png' %}">
                    {% endif %}"

                </div>

            </div>
            <div class="cropper-confirm-no-btn" id="confirm-no-btn"></div>
            <button class="not-visible" id="confirm-btn">Подтвердить</button>


            <div class="input-group">
                {{form.first_name}}
                {{form.last_name}}
            </div>
            <div class="input-group">
                {{form.username}}
                {{form.email}}
            </div>
            <button class="btn-save" type="submit" id="btn_save">Сохранить</button>

        </form>

        <label class="input-file">

            {{form.image}}

            <span class="input-file-btn">Загрузить фото</span>
        </label>


    </div>
</div>
<script>
    let loadFile = function(event) {
       let reader = new FileReader();
         reader.onload = function(){
         let output = document.getElementById('output');
         output.src = reader.result;
         let filename = event.target.files[0].type
         filename = filename.split('/');
             if (filename[0] === 'image'){
         }else{
           alert("Пожалуйста выбирите изображение в формате .jpeg, .jpg, .png или .svg");
         }
       };
         reader.readAsDataURL(event.target.files[0]);
     };

</script>
<script src="{% static 'users/js/main_cropper.js' %}"></script>
{% endblock %}

NMD-server/store/users/templates/users/recovery.html
{% extends 'users/base_login.html'%}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/recovery.css' %}">
{% endblock%}

{% block logo %}
    <a href="{% url 'users:index' %}">
        <img src="{% static 'users/images/NMD_logo.jpg' %}" alt="альтернативный текст" width="95px" height="86px">
    </a>
{% endblock %}
{% block header-title%}
    <div class="header-title"> {{header}}</div>
{% endblock %}

{% block action_button %}
    <form action="/" method="post">
        <input class="input" type="email" name="email" placeholder="Email/Почта">
        <a href="recover-confirm.html">
            <button  class="btn" type="button">Восстановить</button>
        </a>
        <a href="{% url 'users:index' %}">
            <button class="btn" type="button">Назад</button>
        </a>
{% endblock %}

NMD-server/store/users/templates/users/registration.html
{% extends 'users/base_login.html'%}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/registration.css' %}">
{% endblock %}

{% block logo %}
    <a href="{% url 'users:index' %}">
        <img src="{% static 'users/images/NMD_logo.jpg' %}" alt="альтернативный текст" width="95px" height="86px">
    </a>
{% endblock %}
{% block header-title%}
    <div class="header-title"> {{header}}</div>
{% endblock %}

{% block action_button %}
{% if form.errors %}
<div class="container">
    <div class="alert alert-dismissible fade in">
        <a href="#" class="alert-close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>{{form.errors}}</strong>
    </div>
</div>


{% endif %}
<form action="{% url 'users:registration' %}" method="post">
    {% csrf_token %}
    {{ form.email}}
    <button class="btn" type="submit">Зарегистрироваться</button>
    <a href="{% url 'users:index'%}">
        <button class="btn" type="button">Назад</button>
    </a>
</form>


{% endblock %}