NMD-server/store/products/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from products.views import (CartView, FavoritesView, basket_add, basket_remove,
                            cart_add_plus_one, cart_del_minus_one,
                            favorites_add, favorites_remove, item_info,
                            products, remove_all_user_baskets,
                            remove_all_user_favorites, reset_filters,cart_confirm,catalogue)
from django.views.decorators.cache import cache_page

app_name = 'products'
urlpatterns = [
    path('', login_required(products), name='products'),
    path('page/<int:page>/', login_required(products), name='paginator'),
    path('reset/', login_required(reset_filters), name='reset_filters'),
    path('item_info/<str:product_id>', login_required(item_info), name='item_info'),
    path('baskets/add/<str:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>', basket_remove, name='basket_remove'),
    path('cart/', login_required(CartView.as_view()), name='cart'),
    path('baskets/remove/', remove_all_user_baskets, name='remove_all_user_baskets'),
    path('cart/add/<int:basket_id>/', cart_add_plus_one, name='cart_add_plus_one'),
    path('cart/del/<int:basket_id>', cart_del_minus_one, name='cart_del_minus_one'),
    path('favorites/add/<str:product_id>', login_required(favorites_add), name='favorites_add'),
    path('favorites/', login_required(FavoritesView.as_view()), name='favorites'),
    path('favorites/remove/<int:favorite_id>/', favorites_remove, name='favorites_remove'),
    path('favorites/remove/', remove_all_user_favorites, name='remove_all_user_favorites'),
    path('cart/cart_confirm/', cart_confirm,name='cart_confirm'),
    path('catalogue/',catalogue,name='catalogue')
]

NMD-server/store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('products/', include('products.urls', namespace='products')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NMD-server/store/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path
from .views import *



app_name = 'users'
urlpatterns = [
    path('', index, name='index'),
    path('registration/', registration, name='registration'),
    path('registration_confirm/', registration_confirm, name='registration_confirm'),
    path('recovery/', recovery, name='recovery'),
    path('profile/<int:pk>',profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),

]

NMD-server/store/products/models.py
from django.db import models

from users.models import User


class Product(models.Model):
    article = models.CharField(max_length=12, null=False, blank=False, unique=True, primary_key=True)
    model_name = models.CharField(max_length=12, null=False, blank=False)
    model_group = models.CharField(max_length=12, null=False, blank=False)
    img = models.ImageField(upload_to='products_images')
    price = models.DecimalField(max_digits=9, decimal_places=2)
    description = models.TextField(null=True, blank=True)
    full_description = models.TextField(null=True, blank=True)
    color = models.CharField(max_length=24, null=False)
    sizes = models.ForeignKey(to='Size', on_delete=models.CASCADE, to_field='article_size')
    category = models.ForeignKey(to='ProductCategory', on_delete=models.PROTECT, to_field='name')
    product_type = models.ForeignKey(to='ProductType', on_delete=models.PROTECT, to_field='name')
    gender = models.ForeignKey(to='ProductGender', on_delete=models.PROTECT, to_field='name')
    season = models.ForeignKey(to='ProductSeason', on_delete=models.PROTECT, to_field='name')
    age = models.ForeignKey(to='ProductAge', on_delete=models.PROTECT, to_field='name')

    def __str__(self):
        return f"{self.article}"


class ProductAge(models.Model):
    name = models.CharField(max_length=12, null=False, unique=True, primary_key=True)
    userfrendly_name = models.TextField(null=True, blank=True)


class ProductSeason(models.Model):
    name = models.CharField(max_length=12, null=False, unique=True, primary_key=True)
    userfrendly_name = models.TextField(null=True, blank=True)


class ProductGender(models.Model):
    name = models.CharField(max_length=12, null=False, unique=True, primary_key=True)
    userfrendly_name = models.TextField(null=True, blank=True)


class ProductCategory(models.Model):
    name = models.CharField(max_length=12, null=False, unique=True, primary_key=True)
    userfrendly_name = models.TextField(null=True, blank=True)


class ProductType(models.Model):
    name = models.CharField(max_length=12, null=False, unique=True, primary_key=True)
    userfrendly_name = models.TextField(null=True, blank=True)


class Size(models.Model):
    article_size = models.CharField(max_length=12, null=False, unique=True, primary_key=True)
    size_name = models.CharField(max_length=12, null=False, blank=False)
    qty = models.SmallIntegerField()
    to_article = models.CharField(max_length=12, null=False)

    def __str__(self):
        return f"{self.article_size}"


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_qty(self):
        return sum(basket.qty for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, to_field='article')
    size = models.ForeignKey(to=Size, on_delete=models.PROTECT, to_field='article_size')
    qty = models.PositiveSmallIntegerField(default=0)
    create_time_stamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f"Корзина для {self.user.email} товар {self.product.article},размер {self.size.size_name}"

    def sum(self):
        return self.product.price * self.qty


class FavoritesQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(favorites.sum() for favorites in self)

    def total_qty(self):
        return sum(favorites.qty for favorites in self)


class Favorites(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, to_field='article')
    qty = models.PositiveSmallIntegerField(default=0)
    create_time_stamp = models.DateTimeField(auto_now_add=True)
    is_favorite = models.BooleanField(null=False, default=False, blank=False)
    objects = FavoritesQuerySet.as_manager()

    def __str__(self):
        return f"Избранные товары для {self.user.email} товар {self.product.article}"

    def sum(self):
        return self.product.price * self.qty


class SizeSelected(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    create_time_stamp = models.DateTimeField(auto_now_add=True)
    is_selected = models.BooleanField(null=False, default=True, blank=False)

NMD-server/store/products/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import TemplateView
from .context_processors import Basket, Favorites, Product, Size
from django.urls import reverse

from store.utils import *


# Create your views here.


def products(request, page=1):
    filter_dict = {'category__in': ['Shoe', 'Clothes'],
                   'product_type__in': ['Boots', 'Longboots', 'Short_boots', 'Pullover', 'Sneakers','Gaiters'],
                   'gender__in': ['Male', 'Female'], 'season__in': ['Winter', 'Summer','Fall','Spring','Demi'],
                   'age__in': ['Adult', 'Child'], }

    if request.method == 'POST':
        filters = request.POST.getlist('filter_id')
        if len(filters) > 0:
            filter_param_list = []
            for items in filters:
                for k, v in filter_dict.items():
                    if items in filter_dict[k]:
                        filter_param_list.append(k)
                        break
            request.session['filters'] = filters
            current_filters = request.session['filters']
            param_dict = {}
            for param_name in filter_param_list:
                param_dict[param_name] = current_filters
            products = Product.objects.filter(**param_dict).order_by('article')
        else:
            if 'filters' in request.session:
                if request.session['filters']:
                    filter_param_list = []
                    for items in request.session['filters']:
                        for k, v in filter_dict.items():
                            if items in filter_dict[k]:
                                filter_param_list.append(k)
                                break
                    current_filters = request.session['filters']
                    param_dict = {}
                    for param_name in filter_param_list:
                        param_dict[param_name] = current_filters
                    products = Product.objects.filter(**param_dict).order_by('article')
                else:
                    products = Product.objects.all().order_by('article')
            else:
                return HttpResponseRedirect(request.META['HTTP_REFERER'])

    if 'filters' in request.session:
        if request.session['filters']:
            filter_param_list = []
            for items in request.session['filters']:
                for k, v in filter_dict.items():
                    if items in filter_dict[k]:
                        filter_param_list.append(k)
                        break
            current_filters = request.session['filters']
            param_dict = {}
            for param_name in filter_param_list:
                param_dict[param_name] = current_filters
            products = Product.objects.filter(**param_dict).order_by('article')
        else:
            products = Product.objects.all().order_by('article')


        paginator = Paginator(products, per_page=6)
        products_paginator = paginator.page(page)
        context = {
            'title': "Магазин",
            'products': products_paginator,
        }

        return render(request, 'products/products.html', context)
    else:
        products = Product.objects.all().order_by('article')
        paginator = Paginator(products, per_page=6)
        products_paginator = paginator.page(page)
        context = {
            'title': "Магазин",
            'products': products_paginator,
        }
        return render(request, 'products/products.html', context)


def reset_filters(request):
    request.session['filters'] = []
    return HttpResponseRedirect(reverse('products:products'))


def basket_add(request, product_id):
    product = Product.objects.get(article=product_id)
    if request.method == 'POST':
        for article_size in request.POST.getlist('checked_size_id'):
            size = Size.objects.get(article_size=article_size)
            baskets = Basket.objects.filter(user=request.user, product=product, size=size)
            if not baskets.exists():
                Basket.objects.create(user=request.user, product=product, qty=1, size=size)
                baskets = Basket.objects.all().order_by('-create_time_stamp')
                for basket in baskets:
                    basket.save()
            else:
                basket = baskets.last()
                basket.qty += 1
                basket.save()
                baskets = Basket.objects.all().order_by('-create_time_stamp')
                for basket in baskets:
                    basket.save()
        return HttpResponseRedirect(request.META['HTTP_REFERER'])
    else:
        return HttpResponseRedirect(request.META['HTTP_REFERER'])


def cart_add_plus_one(request, basket_id):
    baskets = Basket.objects.filter(user=request.user, id=basket_id)
    basket = baskets.last()
    basket.qty += 1
    basket.save()
    baskets = Basket.objects.all().order_by('-create_time_stamp')
    for basket in baskets:
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def cart_del_minus_one(request, basket_id):
    baskets = Basket.objects.filter(user=request.user, id=basket_id)
    basket = baskets.last()
    basket.qty -= 1
    basket.save()
    baskets = Basket.objects.all().order_by('-create_time_stamp')
    for basket in baskets:
        basket.save()
    if basket.qty == 0:
        basket = Basket.objects.get(id=basket_id)
        basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def basket_remove(request, basket_id):
    Basket.objects.get(id=basket_id).delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def remove_all_user_baskets(request):
    Basket.objects.filter(user=request.user).delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def item_info(request, product_id):
    product = Product.objects.get(article=product_id)
    products = Product.objects.filter(model_group=product.model_group)
    context = {
        'title': "Информация о продукте",
        'product': product,
        'products': products,
    }
    return render(request, 'products/item_info.html', context)


class CartView(DataMixin, TemplateView):
    template_name = 'products/cart.html'
    title = "Корзина"


class FavoritesView(DataMixin, TemplateView):
    template_name = 'products/favorites.html'
    title = "Избранные товары"


def favorites_add(request, product_id):
    product = Product.objects.get(article=product_id)
    favorites = Favorites.objects.filter(user=request.user, product=product)
    if not favorites.exists():
        favorite = Favorites.objects.create(user=request.user, product=product, qty=1, is_favorite=True)
        favorite.save()
    else:
        favorite = Favorites.objects.get(product=product_id, user=request.user)
        favorite.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def favorites_remove(request, favorite_id):
    Favorites.objects.get(id=favorite_id, user=request.user).delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def remove_all_user_favorites(request):
    Favorites.objects.filter(user=request.user).delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def cart_confirm(request):
    Basket.objects.filter(user=request.user).delete()
    context = {
        'title': "Заказ подтвержден",

    }
    return render(request, 'products/cart_confirm.html', context)

def catalogue(request):

    context = {
        'title': "Каталог",

    }
    return render(request, 'products/catalogue.html', context)

NMD-server/store/products/templates/products/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

NMD-server/store/products/templates/products/base_products.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="//fonts.googleapis.com">
    <link rel="preconnect" href="//fonts.gstatic.com" crossorigin>
    <link href="//fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'products/js/jquery-3.7.1.min.js' %}"></script>
    <link  href="{% static 'users/css/cropper.css' %}" rel="stylesheet">
    <script src="{% static 'users/js/cropper.js' %}"></script>






    {{ form.media }}


    {% block css%}

    {% endblock %}
    <title>{{title}}</title>
</head>
<body>
<div class="page">
    <header class="header">

        <div class="logo">
            {% block logo %}

            {% endblock %}
        </div>

        <div class="nav-bar-group">
            <a href="{% url 'products:catalogue'%}">
                <div class="catalogue"><img src="{% static 'products/images/line.png' %}">
                    </svg>КАТАЛОГ
                </div>
            </a>

            <form action="#" method="get">
                <input class="search-field" type="search" name="search" placeholder="Поиск">
                <svg class="magnifier" width="64px" height="64px" viewBox="0 0 24 24" fill="none"
                     xmlns="http://www.w3.org/2000/svg" stroke="#C0BFBF">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                        <path d="M11 6C13.7614 6 16 8.23858 16 11M16.6588 16.6549L21 21M19 11C19 15.4183 15.4183 19 11 19C6.58172 19 3 15.4183 3 11C3 6.58172 6.58172 3 11 3C15.4183 3 19 6.58172 19 11Z"
                              stroke="" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                    </g>
                </svg>
            </form>

            <div class="icons">
                <a href="{% url 'users:profile' user.id %}">
                    <div class="dropdown">
                        <svg class="human" fill="#C0BFBF" viewBox="0 0 200 200" data-name="Layer 1" id="Layer_1"
                             xmlns="http://www.w3.org/2000/svg">
                            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                            <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                            <g id="SVGRepo_iconCarrier"><title></title>
                                <path d="M169,170.71l-2-4a73.78,73.78,0,0,0-31-32,66.14,66.14,0,0,0,29-54.5,65,65,0,1,0-101,54,73.78,73.78,0,0,0-31,32l-2,4a10.06,10.06,0,0,0,18,9l2-4a55,55,0,0,1,98,0l2,4a10,10,0,0,0,13.5,4.5c5-2,7-8,4.5-13ZM55,80.21a45,45,0,1,1,45,45A44.81,44.81,0,0,1,55,80.21Z"></path>
                            </g>
                        </svg>
                        <div class="dropdown-content">
                            {% if user.is_superuser or user.is_stuff %}
                            <div class="drop-row"><a href="{% url 'users:profile' user.id %}">Профиль</a></div>
                            <div class="drop-row"><a href="{% url 'admin:index' %}">Admin</a></div>
                            <div class="drop-row"><a href="{% url 'users:password_change' %}">Сменить пароль</a></div>
                            <div class="drop-row"><a href="{% url 'users:logout' %}">Выйти</a></div>
                            {% else %}
                            <div class="drop-row"><a href="{% url 'users:profile' user.id %}">Профиль</a></div>
                            <div class="drop-row"><a href="{% url 'users:logout' %}">Выйти</a></div>
                            {% endif %}
                        </div>
                    </div>
                </a>
                <a href="{% url 'products:favorites' %}">
                    <svg class="heart" fill="#C0BFBF" viewBox="0 0 200 200" data-name="Layer 1" id="Layer_1"
                         xmlns="http://www.w3.org/2000/svg">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier"><title></title>
                            <path d="M171.28,41.69a48.29,48.29,0,0,0-68.5,0l-2.5,3-2.5-2.5a48.29,48.29,0,0,0-68.5,0c-19,18.5-19,49-1,68l50,53a29.92,29.92,0,0,0,43.5,0l50.5-53.5c17.5-19.5,17-49.5-1-68Zm-14,53.5-50.5,53.5a10.26,10.26,0,0,1-14.5,0l-50-53c-10.5-11.5-10.5-29,.5-40s29-11,40.5,0l2.5,2.5c8,8,20.5,8,28,0l2.5-2.5a28.37,28.37,0,0,1,40,0,27.78,27.78,0,0,1,1,39.5Z"></path>
                        </g>
                    </svg>
                </a>

                <a href="{% url 'products:cart' %}">
                    <svg class="cart" fill="#C0BFBF" viewBox="-2 -2 204.00 204.00" data-name="Layer 1" id="Layer_1"
                         xmlns="http://www.w3.org/2000/svg">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier"><title></title>
                            <path d="M183.25,52.75a18.22,18.22,0,0,0-7-1h-91c-3.5,0-8-.5-11.5.5a9.64,9.64,0,0,0-7.5,9.5,10,10,0,0,0,10,10h90.5l-8,42a10.22,10.22,0,0,1-10,8h-75a10.66,10.66,0,0,1-10-8l-16-74a20.3,20.3,0,0,0-19.5-16h-7a10,10,0,0,0,0,20h7l16,74c3,14,15,23.5,29.5,23.5h75c12,0,24.5-8,28-19.5,2.5-8,4-17,5.5-25,1.5-8.5,3.5-17,5-25a17.76,17.76,0,0,0,1-5,17,17,0,0,0,.5-5c0-4-2-8-5.5-9Zm-132,108.5a15,15,0,0,0,30,0h0a15,15,0,0,0-30,0Zm90,0a15,15,0,1,0,15-15,15,15,0,0,0-15,15v0Z"></path>
                        </g>
                    </svg>
                </a>
                <div class="counter-icon-group">

                    {% if not favorites.total_qty == 0 %}
                    <div class="heart-counter">{{favorites.total_qty}}</div>
                    {% endif %}

                    {% if not baskets.total_qty == 0%}
                    <div class="cart-counter">{{baskets.total_qty}}</div>
                    {% endif %}
                </div>

            </div>
        </div>


    </header>
    <main class="main">

        {% block content%}

        {% endblock %}

    </main>
    <footer class="footer">{{footer_info}}<br>{{footer_info_2}}</footer>
</div>


<!--	div page end-->

</body>
</html>

NMD-server/store/products/templates/products/cart_confirm.html
{% extends 'products/registration_confirm.html'%}

{% load static %}

{% load products_tags %}

{% block css%}
<link rel="stylesheet" href="{% static 'products/css/cart_confirm.css' %}">
<script type="text/javascript" src="{% static 'products/js/jquery-3.7.1.js' %}"></script>
{% endblock %}


{% block logo %}
<a href="{% url 'products:products' %}">
    <img src="{% static 'products/images/NMD_logo.jpg' %}" alt="альтернативный текст" width="95px" height="86px">
</a>
{% endblock %}


{% block action_button %}
<div class="cart-confirm-info">Ваш заказ успешно оформлен</div>
<a href="{% url 'products:products' %}">
        <button class="btn" type="button">На главную</button>
    </a>

{% endblock %}

NMD-server/store/products/templates/products/popup.html
<!--popup block-->
<div class="popup">
    <div class="popup-body">
        <div class="popup-content">
            <a class="popup-close" href="#">Закрыть &#935;</a>
            <div class="popup-title"> Выберите размер:</div>

                {% if not fav %}
                <div class="size-group">
                <form action="" method="post">
                    {% csrf_token %}
                    {% for size in sizes %}
                    {% if product.article == size.to_article %}
                    <label>
                        <input class="size-popup-checkbox" data="{{product.article}}"  type="checkbox"
                               name="checked_size_id"
                               value="{{size}}">
                        <div class="title-popup-checkbox">{{size.size_name}}</div>
                    </label>
                    {% endif %}
                    {% endfor %}


            <button class="btn-popup" onclick="isChecked()" data="{{product.article}}" name="btn2"
                            formaction="{% url 'products:basket_add' product.article  %}"
                            type="submit">
                        <svg class="popup-button-cart" fill="#C0BFBF" width="64px" height="64px"
                             viewBox="-2 -2 204.00 204.00"
                             data-name="Layer 1" id="Layer_1" xmlns="http://www.w3.org/2000/svg">
                            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                            <g id="SVGRepo_tracerCarrier" stroke-linecap="round"
                               stroke-linejoin="round"></g>
                            <g id="SVGRepo_iconCarrier"><title></title>
                                <path d="M183.25,52.75a18.22,18.22,0,0,0-7-1h-91c-3.5,0-8-.5-11.5.5a9.64,9.64,0,0,0-7.5,9.5,10,10,0,0,0,10,10h90.5l-8,42a10.22,10.22,0,0,1-10,8h-75a10.66,10.66,0,0,1-10-8l-16-74a20.3,20.3,0,0,0-19.5-16h-7a10,10,0,0,0,0,20h7l16,74c3,14,15,23.5,29.5,23.5h75c12,0,24.5-8,28-19.5,2.5-8,4-17,5.5-25,1.5-8.5,3.5-17,5-25a17.76,17.76,0,0,0,1-5,17,17,0,0,0,.5-5c0-4-2-8-5.5-9Zm-132,108.5a15,15,0,0,0,30,0h0a15,15,0,0,0-30,0Zm90,0a15,15,0,1,0,15-15,15,15,0,0,0-15,15v0Z"></path>
                            </g>
                        </svg>
                        В корзину
                    </button>
                    </form>
                    </div>

                {% else %}
                <div class="size-group">
                <form action="" method="post">
                    {% csrf_token %}
                    {% for size in sizes %}
                    {% if favorite.product.article == size.to_article %}
                    <label>
                        <input class="size-popup-checkbox" data="{{favorite.product.article}}"  type="checkbox"
                               name="checked_size_id"
                               value="{{size}}">
                        <span class="title-popup-checkbox">{{size.size_name}}</span>
                    </label>
                    {% endif %}
                    {% endfor %}

                    <button class="btn-popup" onclick="isChecked()" data="{{favorite.product.article}}" name="btn2"
                            formaction="{% url 'products:basket_add' favorite.product.article  %}"
                            type="submit">
                        <svg class="button-cart" fill="#C0BFBF" width="64px" height="64px"
                             viewBox="-2 -2 204.00 204.00"
                             data-name="Layer 1" id="Layer_1" xmlns="http://www.w3.org/2000/svg">
                            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                            <g id="SVGRepo_tracerCarrier" stroke-linecap="round"
                               stroke-linejoin="round"></g>
                            <g id="SVGRepo_iconCarrier"><title></title>
                                <path d="M183.25,52.75a18.22,18.22,0,0,0-7-1h-91c-3.5,0-8-.5-11.5.5a9.64,9.64,0,0,0-7.5,9.5,10,10,0,0,0,10,10h90.5l-8,42a10.22,10.22,0,0,1-10,8h-75a10.66,10.66,0,0,1-10-8l-16-74a20.3,20.3,0,0,0-19.5-16h-7a10,10,0,0,0,0,20h7l16,74c3,14,15,23.5,29.5,23.5h75c12,0,24.5-8,28-19.5,2.5-8,4-17,5.5-25,1.5-8.5,3.5-17,5-25a17.76,17.76,0,0,0,1-5,17,17,0,0,0,.5-5c0-4-2-8-5.5-9Zm-132,108.5a15,15,0,0,0,30,0h0a15,15,0,0,0-30,0Zm90,0a15,15,0,1,0,15-15,15,15,0,0,0-15,15v0Z"></path>
                            </g>
                        </svg>
                        В корзину
                    </button>
                </form>
                </div>
                {% endif %}
        </div>
    </div>
</div>
</div>

<!--end popup block-->

NMD-server/store/products/templates/products/registration_confirm.html
{% extends 'users/base_login.html'%}


{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/registration_confirm.css' %}">
{% endblock%}
{% block logo %}
    <a href="{% url 'users:index' %}">
        <img src="{% static 'users/images/NMD_logo.jpg' %}" alt="альтернативный текст" width="95px" height="86px">
    </a>
{% endblock %}
{% block header-title%}
    <div class="header-title"> {{header}}</div>
{% endblock %}

{% block action_button %}
    <a href="{% url 'users:index' %}">
        <button class="btn" type="button">На главную</button>
    </a>
{% endblock %}